# -*- coding: utf-8 -*-

# NINGUNA UNIDAD DE NAMESPACE EN PYTHON DEBERIA LLAMARSE TESTS
# SI NO SE TRATA DE TESTS UNITARIOS, FUNCIONALES O DE INTEGRACION.
# ESTE DIRECTORIO VUELA (O COMO MUCHO SE RENOMBRA A LABS O ALGO ASI).

